# Create a bind master
- hosts: bind

  vars:
    
  tasks:
    - name: firewall daemon
      action: package name=firewalld state=installed

    - name: firewall python module
      action: package name=python-firewall state=installed
      
    - name: install bind utilities
      action: package name=bind-utils state=installed

    - name: install bind server
      action: package name=bind state=installed

    - name: firewall service
      action: systemd name=firewalld enabled=yes state=started
      
    - name: dns service
      action: systemd name=named enabled=yes state=started

    - name: dns port
      action: firewalld zone=public service=dns state=enabled permanent=yes immediate=yes

    - name: named configuration file
      action: template src=../templates/named.conf.j2 dest=/etc/named.conf
    
- hosts: masters
  vars:
    
  tasks:

    # On RHEL7 this is python-dns.  On F25 it's python2-dns
    - name: install python DNS package
      action: package name=python2-dns state=installed
      when: (ansible_distribution == "Fedora")

    - name: install python DNS package
      action: package name=python-dns state=installed
      when: (ansible_distribution == "RHEL" or ansible_distribution == "CentOS")

    - name: named master zone configuration file(s)
      action: template src=../templates/zones.conf-master.j2 dest=/etc/named/zones.conf
      notify:
      - restart named
    
    - name: set zone update key
      action: template src=../templates/update.key.j2 dest=/etc/named/update.key
      notify:
      - restart named

    - name: set zone data file(s)
      action: template src=../templates/zone.db.j2 dest=/var/named/dynamic/zone.db owner=named group=named
      tags:
        - zonedata
      notify:
      - restart named
  
  handlers:
    - name: restart named
      systemd: name=named state=restarted

      
- hosts: slaves

  vars:

  tasks:
    - name: named slave zone configuration file(s)
      action: template src=../templates/zones.conf-slave.j2 dest=/etc/named/zones.conf
      notify:
      - restart named

    - name: set zone update key
      action: template src=../templates/update.key.j2 dest=/etc/named/update.key
      notify:
      - restart named

  handlers:
    - name: restart named
      systemd: name=named state=restarted
