# Create a bind master
- hosts: bind
  user: vagrant
  become: yes

  vars:
    
  tasks:
    - name: firewall daemon
      action: dnf name=firewalld state=installed

    - name: firewall python module
      action: dnf name=python-firewall state=installed
      
    - name: install bind utilities
      action: dnf name=bind-utils state=installed

    - name: install bind server
      action: dnf name=bind state=installed

    - name: firewall service
      action: systemd name=firewalld enabled=yes state=started
      
    - name: dns service
      action: systemd name=named enabled=yes state=started

    - name: dns port
      action: firewalld zone=public service=dns state=enabled permanent=yes immediate=yes

    - name: named configuration file
      action: template src=../templates/named.conf.j2 dest=/etc/named.conf
      notify:
      - restart named

  handlers:
    - name: restart named
      systemd: name=named state=restarted
    
- hosts: masters
  user: vagrant
  become: yes

  vars:
    
  tasks:
    - name: named master zone configuration file(s)
      action: template src=../templates/zones.conf-master.j2 dest=/etc/named/zones.conf
      notify:
      - restart named
    
    - name: set zone update key
      action: template src=../templates/update.key.j2 dest=/etc/named/update.key
      notify:
      - restart named

    - name: set zone data file(s)
      action: template src=../templates/zone.db.j2 dest=/var/named/dynamic/zone.db owner=named group=named
      notify:
      - restart named

  handlers:
    - name: restart named
      systemd: name=named state=restarted

      
- hosts: slaves
  user: vagrant
  become: yes

  vars:

  tasks:
    - name: named slave zone configuration file(s)
      action: template src=../templates/zones.conf-slave.j2 dest=/etc/named/zones.conf
      notify:
      - restart named

    - name: set zone update key
      action: template src=../templates/update.key.j2 dest=/etc/named/update.key
      notify:
      - restart named

#    - name: set zone data file(s)
#      action: template src=../templates/zone.db.j2 dest=/var/named/dynamic/zone.db owner=named group=named
#      notify:
#      - restart named

  handlers:
    - name: restart named
      systemd: name=named state=restarted

